# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  tests:  # id of input
    description: 'Who to greet'
    required: true
    default: 'Boom'
outputs:
  testsList: # id of output
    description: 'The list of tests created'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.tests }}
