name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]
  repository_dispatch:
    types:
      - test

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TESTS: ['boom']
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Setup Node Modules
        uses: bahmutov/npm-install@v1
      - env:
          TESTS: ${{ github.event.client_payload.tests }}
        run: make tests -e TESTS=$TESTS
      # - name: Install Playwright Browsers
      #   run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: yarn run test:execute
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 30
      # - uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: serenity-report
      #     path: target/site/serenity
      #     retention-days: 30

      - name: Move Playwright reports
        run: mv playwright-report target/site/playwright

      # - name: GitHub Pages
      #   if: github.ref == 'refs/heads/main'
      #   uses: JamesIves/github-pages-deploy-action@v4.5.0
      #   with:
      #     ssh-key: ${{ secrets.DEPLOY_KEY }}
      #     BRANCH: gh-pages
      #     FOLDER: target/site/playwright
      #     CLEAN: true
